# Simple docker-compose.yml
# You can change your port or volume location

version: '3.7'

services:
  nginx: 
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    ports:
      - 80:80
      - 443:443  
    networks:
      - "net"

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes: 
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --force-renewal --email guillermo_432@hotmail.com -d observabilidadbp.eastus.cloudapp.azure.com --agree-tos        


  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    volumes:
      - ./uptime-kuma-data:/app/data
    ports:
      - 3001:3001  # <Host Port>:<Container Port>
    restart: always
    networks:
      - "net"
    environment:
    - VIRTUAL_HOST=observabilidadbp.eastus.cloudapp.azure.com
    - VIRTUAL_PORT=3001

networks:
  net:
    external: true
